# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - ledgerNest

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      - name: Publish app
        run: dotnet publish backend/src/FinanceTracker.Api/FinanceTracker.Api.csproj -c Release -o ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ledgerNest
          slot-name: Production
          package: ./publish
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_05457C2766084CB5A867F76C20DC3D92 }}
